### ISSUE TITLE
[Bug] Buttons for civitai-helper in Extra Networks is hidden in 1.3.0

### ISSUE THREAD

**Issue by Koikaiko** [lobehub/sd-webui-lobe-theme#105]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Thank you for the wonderfully designed UI.

After upgrading webui to 1.3.0, the civitai-helper button no longer appears.

It is not visible on the Extra Network thumbnail with all preview images and I cannot press the button.
The button is visible before the preview images are loaded. As soon as the preview image is displayed, it is hidden behind the preview image.
The Default view for Extra Networks is set to thums.

![2023-05-30 02 06 26](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/110581151/eeee16f0-ee28-4cc3-ab0b-49ad59cddf01)

If this problem is from webui, please ignore this talk.

Translated with www.DeepL.com/Translator (free version)

(Original)
素晴らしいデザインのUIをありがとうございます。
webuiを1.3.0にしたら、civitai-helperのボタンが表示されなくなりました。
すべてのプレビュー画像のあるExtra Networkのサムネイル上で表示されず、ボタンを押せません。
プレビュー画像のロード前には、ボタンが見えています。プレビュー画像が表示されるとともに、プレビュー画像の後ろに隠れてしまいます。
Default view for Extra Networksの項目はthumsにしています。

この問題がwebuiのものであったら、この話しは無視してください。

**Comment by SebSaga** [comment]
I was able to fix this by going into the Auto1111 settings -> Extra Networks -> Then changing "Default View For Extra Networks" to Cards instead of Thumbs. I applied the changes and reloaded the UI and it works now.

Hope this helps!
