### ISSUE TITLE
[Bug] 插件兼容性问题 stable-diffusion-webui-state

### ISSUE THREAD

**Issue by Policturn** [lobehub/sd-webui-lobe-theme#106]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

stable-diffusion-webui-state这个插件是用来在打开webui时自动保留上一次设置和词条的,在使用的时候会出现高清修复部分如果上一次是开启的,这一次保留开启状态时会直接把设置部分吞掉,显示不出来
插件地址https://github.com/ilian6806/stable-diffusion-webui-state

![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/88045047/1f729c4a-eefb-4aa5-94b6-bf3dab716117)

**Comment by robonxt** [comment]
I'm also experiencing the same issue as well. Could it be related to #217 as well, where the extensions are fighting over who gets the control of the textboxes/checkboxes?
