### ISSUE TITLE
[Bug] Squashed Folder Names

### ISSUE THREAD

**Issue by HaydenReeve** [lobehub/sd-webui-lobe-theme#109]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

When using long folder names or subfolders, directory previews at the top get cramped and unreadable.

![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/39004735/fd5b06f1-0d64-42d2-b4c6-02a190a19e7a)

### 🚦 期望结果 | Expected Behavior

Readable (expanded) buttons or a dropdown to select desired folders. Alternatively, deeper sorting options using labels or tags.

### 📷 复现步骤 | Recurrence Steps

Create a folder within a LORA, Stable Diffusion, or any other folder. Call it "Anime," then create a subfolder and call it "Flat Shading."

If you repeat this several times with several categories you will end up with a screenshot such as above.

### 📝 补充信息 | Additional Information

Thank you for all of your hard work, it is very appreciated and loved!

**Comment by chrisbward** [comment]
Would be good to have a toggle to hide these completely, or display just the first n levels.
