### ISSUE TITLE
[Request] 请求添加一个插件启用状况显示的功能

### ISSUE THREAD

**Issue by anne43983959** [lobehub/sd-webui-lobe-theme#118]
### 🥰 需求描述 | Feature Description

controlnet添加了自己的启用状态显示开关，如下图所示
![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/115604775/5e190bf4-967a-4cee-a10c-218db12ba660)
更早的时间，曾有一个叫enable checker的插件也有类似的功能，但它与kitchen theme冲突，且检测有延迟，希望后续版本中能添加类似功能，指示插件的启用状态

### 🧐 解决方案 | Proposed Solution

由于各插件启用的选项不完全相同，可以借用1.3.1版本更改预设功能中检查设置变更的功能，让用户分别设置所有插件为全关和全开两种状态，检测差异，获取所有插件需要检测的选项

另，希望重新恢复独立的设置选项卡，以便于添加汉化支持

同时希望能修复附加网络面板显示方式与设置中的选项不符的情况，如下图所示，附加网络面板是悬浮状态，但设置中却显示是fixed，切换到float保存并重启后，虽然实际上确实切换到了float，但是设置中依然显示的是fixed（快捷设置侧边栏就没有这个bug）
![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/115604775/3d2d40f1-523b-4f73-9425-094f0e435be4)
![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/115604775/fe14b71c-7759-4151-8c0b-ec98b9c9365d)

**Comment by canisminor1990** [comment]
float 问题已修复
