### ISSUE TITLE
[Bug] LORA Metadata not accessable

### ISSUE THREAD

**Issue by mccabedd** [lobehub/sd-webui-lobe-theme#133]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Firefox

### 🐛 问题描述 | Bug Description

Don't know if this is a bug, or if it would be filed under Feature request, but without the Kitchen Theme, I can access the LORA metadata by clicking on the (i) icon.

![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/30120074/3f0e7727-5be3-4e5e-8c4a-da9210988459)

With the Kitchen Theme, the (i) icon is unavailable

### 🚦 期望结果 | Expected Behavior

By clicking the (i) icon on the top right-hand side of Additional Networks/Loras, the Lora metadata page would appear

**Comment by kadevin** [comment]
Chrome 和 Edge 也是一样，因为这个问题我换回系统原主题了
