### ISSUE TITLE
[Request] Option to keep floating sidebar until the close button is pressed

### ISSUE THREAD

**Issue by MeeJay** [lobehub/sd-webui-lobe-theme#135]
### 🥰 需求描述 | Feature Description

Actually, the sidebar menus (like the Extra Network's one) are either fixed (and take space on the main window of Automatic1111) either floating, but if you set them as Floating, they'll open automatically when you hover them with your mouse cursor, and close automatically when your cursor is not anymore on them.
The issue is that the menu are closing too quick and I often need to hover them again from the side.

### 🧐 解决方案 | Proposed Solution

Like one can choose between Fixed or Float menu, is it possible to add a "Floating Fixed" option that'll work like the Fixed menu (By clicking on the arrow to open and close) but that'll make the menu appear above the main page, so Automatic1111 interface will not be cropped ?
Another option would be to add a 1 second delay after the mouse is going outside the menu before closing it, or let user specify the delay.

**Comment by canisminor1990** [comment]
Add pin button in v2.0.0

**Comment by amimi818** [comment]
太需要这个"Floating Fixed" 选项了，希望：
1. 当鼠标触发sidebar悬浮出来之后，不自动收回，保持悬浮状态；
2. 当鼠标点击除sidebar之外的任何区域后，sidebar再收回。
---
This "Floating Fixed" option is much needed：
1. when the mouse triggers the sidebar to hover out, it does not automatically retract and remains hovered;
2. when the mouse clicks on any area other than the sidebar, the sidebar retracts.

**Comment by MeeJay** [comment]
> 太需要这个"Floating Fixed" 选项了，希望：
> 
> 1. 当鼠标触发sidebar悬浮出来之后，不自动收回，保持悬浮状态；
> 2. 当鼠标点击除sidebar之外的任何区域后，sidebar再收回。
> 
> This "Floating Fixed" option is much needed：
> 
> 1. when the mouse triggers the sidebar to hover out, it does not automatically retract and remains hovered;
> 2. when the mouse clicks on any area other than the sidebar, the sidebar retracts.

That's exactly what I had in mind!
