### ISSUE TITLE
[Request] 大的4k显示器下用太费眼睛

### ISSUE THREAD

**Issue by cliffcat** [lobehub/sd-webui-lobe-theme#141]
### 🥰 需求描述 | Feature Description

试用了1小时，大的4k显示器下用太费眼睛，又小配色看着累，不适合长时间使用，

### 🧐 解决方案 | Proposed Solution

希望能缩放UI，否则太小了费眼睛，总感觉有0.1s的卡顿，原版的样式就很流畅丝滑。开发者看情况修改吧。

**Comment by Aincvy** [comment]
我感觉有 0.1 - 0.2秒的卡顿， 没有kitchen 那么丝滑。。
