### ISSUE TITLE
[Bug] 看不到进度条，批量生成的图片不能发送到图生图，重绘等

### ISSUE THREAD

**Issue by jinjin327** [lobehub/sd-webui-lobe-theme#151]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

还是看不到进度条，点击单个图片放大观看不能翻页（左右箭头没用），不能把单张图片发送到图生图，局部重绘等

**Comment by canisminor1990** [comment]
进度条的问题无法复现，有其他插件占据那个位置么

**Comment by luuIlee** [comment]
看不到生成实时过程图以及进度条,浏览器顶部标签栏能够显示进度
