### ISSUE TITLE
[Bug] ExtraNetworks UI

### ISSUE THREAD

**Issue by cratom4** [lobehub/sd-webui-lobe-theme#156]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

1. Folder list get scrolled along with models
2. Scroll get stuck at the end of model list (Moving the cursor allows scrolling again but it scrolls entire network page, and also the main division if I scroll further)

### 🚦 期望结果 | Expected Behavior

1. Folder list to be shown under refresh button even after scrolling down the model list
2. Able to scroll to the end of the list without moving cursor, and not scrolling other areas

**Comment by cratom4** [comment]
Maybe I didn't explain enough, I want these buttons to be fixed on top of the extra network list.

Expected: Scroll only models, not the buttons.

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/133774119/553626dc-4914-4f93-9f73-f9704b40427e)

**Comment by SirVeggie** [comment]
The possible problem with this is that there can be a case where the user has a lot of sub folders, so the quick navigation buttons will take too much space.
