### ISSUE TITLE
[Bug] 2.0升级后再次出现了无效的UI空位

### ISSUE THREAD

**Issue by gzizumi** [lobehub/sd-webui-lobe-theme#157]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

升级后曾经反馈过的UI问题又出现了 多了这几种空位，文生图图生图都有
<img width="639" alt="屏幕截图 2023-06-28 144156" src="https://github.com/canisminor1990/sd-webui-lobe-theme/assets/132351461/dfc4df74-0bce-43d2-a3b5-b94462c96b5b">
<img width="339" alt="屏幕截图 2023-06-28 144222" src="https://github.com/canisminor1990/sd-webui-lobe-theme/assets/132351461/d11ddfdb-367f-4397-ba2d-5462efb27bd3">
<img width="367" alt="屏幕截图 2023-06-28 144249" src="https://github.com/canisminor1990/sd-webui-lobe-theme/assets/132351461/57ca9296-3d22-4be4-a3d0-64f6d43d3f32">
<img width="295" alt="image" src="https://github.com/canisminor1990/sd-webui-lobe-theme/assets/132351461/3f09e4d7-7b9f-4338-9e9c-ddbd5fc4072c">

### 🚦 期望结果 | Expected Behavior

应该是删除或禁用某些插件造成的空位，原版ui没有这个问题，望更正谢谢OvO

**Comment by Kuron88** [comment]
升级到2.2.2后，这个问题依然存在
