### ISSUE TITLE
[Bug] “文生图”发送到“图生图“对应ID错误

### ISSUE THREAD

**Issue by liulsg** [lobehub/sd-webui-lobe-theme#163]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

问题1.如果文生图一次生成了多张图片，不管选中哪一张图片，发送到图生图（图生图中的重绘）的图片都是总批次的目录图。
发送后后期处理同样的错误。
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/97494068/0a4fcdd6-e01d-4536-b0d4-c2ecab35856a)

问题2.ctrl/alt+enter 生成快捷键失效

**Comment by canisminor1990** [comment]
暂时可在设置里关掉 split previewer 解决，还在想办法

**Comment by liulsg** [comment]
> 暂时可在设置里关掉分割预览器解决，还在想办法

不知道能不能先修复此BUG.
