### ISSUE TITLE
[Bug] UI界面出现的空白位，2.0-2.4.1都没修复这个问题

### ISSUE THREAD

**Issue by Kuron88** [lobehub/sd-webui-lobe-theme#187]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![QQ截图20230630121327](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/29248355/8ba22344-f167-4f03-add5-74b69bed8a6a)

这个空白占位什么时候修复下

### 🚦 期望结果 | Expected Behavior

去掉这样的空白占位

**Comment by canisminor1990** [comment]
看着小 但有点难解

**Comment by canisminor1990** [comment]
目前暂时移除一个，还有一个暂时没找到可靠的方法

**Comment by gzizumi** [comment]
> 目前暂时移除一个，还有一个暂时没找到可靠的方法

加加油OvO
