### ISSUE TITLE
[Bug] Seed number doesn't change when multiple images are generated

### ISSUE THREAD

**Issue by cratom4** [lobehub/sd-webui-lobe-theme#192]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

Selecting different images in result doesn't change seed number in generation info.
When clicked on save, it saves all generated images including grid, and "send to" button sends grid instead of selected image.
Also, arrow key/button to switch between images doesn't work when zoomed.

### 📷 复现步骤 | Recurrence Steps

Generate multiple images.

**Comment by cratom4** [comment]
Seems like issue occurs only when split previewer is turned on.

**Comment by Kryptonic83** [comment]
yep, verified i'm having the same problems with split previewer enabled. Nice feature but a deal breaker if the seeds don't update and can't arrow through images full view.
