### ISSUE TITLE
[Bug] 生成过程中，最开始有进度，但是当开始预览图片效果以后，缺少实时进度的展示

### ISSUE THREAD

**Issue by zicator** [lobehub/sd-webui-lobe-theme#202]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

希望一直展示完整的时长和进度文字信息；
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/54298150/e36d7512-5c21-4c39-9b20-d309b1fcb3be)
生成过程中，最开始有进度，但是当开始预览图片效果以后，缺少实时进度的展示
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/54298150/2d2b40fb-d323-42aa-b301-22fba693e7ec)

**Comment by zicator** [comment]
希望能快一点改，我本地改这一个参数已经调整过来了，但是希望能够接收官方的更新
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/54298150/1fbb548f-82d9-4fa1-b25f-b85394a20c5d)

**Comment by eplay6** [comment]
@zicator 从哪改，教教我，我的直接不显示，谢谢啊
