### ISSUE TITLE
[Bug] not centered first tab on mobile launch

### ISSUE THREAD

**Issue by robonxt** [lobehub/sd-webui-lobe-theme#209]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

First of all, just wanted to say thank you to making this theme.

When opening the webui on mobile portrait orientation, the first tab that loads up does not have things centered (maybe because it tries to load up the side bars like on desktop?) But after I rotate to landscape and back again, it centers itself.

![Screenshot_2023-07-01-14-09-41-91_7bf062b6cfa832b34bb8e1c056ab1fa0](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/8854735/7536195c-aeaa-4a02-8e44-f38a7879433f)

### 🚦 期望结果 | Expected Behavior

Loading up the webui should have the options properly centered no matter what orientation.

### 📷 复现步骤 | Recurrence Steps

1. Install theme
2. Open webui on mobile in portrait orientation
3. Make sure extra network sidebar is enabled
4. Save and reload the webui
5. Notice uncentered options

### 📝 补充信息 | Additional Information

I wonder does it have to do with the theme loading up the side bars first and then realizing that the screen can't fit it, so it hides it away, but since there was a slide out button on desktop/landscape, that button takes up part of the screen?

Fresh launch:
![Screenshot_2023-07-01-14-09-41-91_7bf062b6cfa832b34bb8e1c056ab1fa0](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/8854735/d4f6f281-6f62-463f-ac9d-3e2c93cfccde)

Rotate to landscape and back to portrait:
![Screenshot_2023-07-01-14-09-57-16_7bf062b6cfa832b34bb8e1c056ab1fa0](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/8854735/9e892e69-11d1-47ef-8b60-b7399a23163a)

May be related to #207 ?

**Comment by SirVeggie** [comment]
Unlikely to be related to #207.

**Comment by robonxt** [comment]
I've tested this out with a desktop computer as well, and if you try to load the WebUI in a small narrow window, it looks as if it wanted to load the generated result viewpoint on the right, but then it realizes that it can't fit, so it goes in row. However, because of that, the bottom options (especially those in a accordion) do not know the full size of the screen, and thus are either using less than 100% of width, or in the case of ControlNet, it extends beyond the screen. Temporary fix is to rotate or resize the screen so the WebUI gets "refreshed" on the screen width

**Comment by robonxt** [comment]
Here's a recording of it on my desktop. It's the same on the phone, but the workaround there is to rotate the phone for it to switch orientation.

https://github.com/canisminor1990/sd-webui-lobe-theme/assets/8854735/06dda879-356e-4be0-8408-dee1a4efc539
