### ISSUE TITLE
[Bug] --gradio-auth doesn't work with theme

### ISSUE THREAD

**Issue by Aosneg** [lobehub/sd-webui-lobe-theme#214]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

When i set command arg --gradio-auth username:password, I couldn't reach login page if lobe theme is active. Instead, i got lobe theme logo and endlessly spinning loading circle. But if I start without theme and then activate it through extensions tab, it works well and login page appears until i relaunch my webui.

### 🚦 期望结果 | Expected Behavior

Login page have to work with theme.

### 📷 复现步骤 | Recurrence Steps

set COMMANDLINE_ARGS= --gradio-auth username:password and launch webui

**Comment by Inblac** [comment]
same problem

**Comment by BaiterYamato** [comment]
same
