### ISSUE TITLE
[Request] Option to hide top left "LobeTheme | SD" sign 

### ISSUE THREAD

**Issue by younyokel** [lobehub/sd-webui-lobe-theme#226]
### 🥰 需求描述 | Feature Description

I would like the option to hide the "LobeTheme | SD" sign all together with logo, url and text as well as the padding on the left side to the icon. All of it removed, allows me to view more tabs without needing to scroll, and I think it looks pretty😊

### 🧐 解决方案 | Proposed Solution

Html or something

**Comment by robonxt** [comment]
There's a option in settings that allows you to change the text and icon of it, although I'm not sure if you can completely remove the icon and text

**Comment by younyokel** [comment]
> There's a option in settings that allows you to change the text and icon of it, although I'm not sure if you can completely remove the icon and text

I am aware of that. just for a test i tried removing the line that puts the icon using web inspector and there's still a padding that leaves space on the left side of the tabs list that i couldn't change for some reason

**Comment by robonxt** [comment]
Yeah, sadly that seems to be the issue. Submit a bug report?
