### ISSUE TITLE
[Bug] 启用lobe theme会影响文生图预览图的生成过程显示

### ISSUE THREAD

**Issue by jasoncow007** [lobehub/sd-webui-lobe-theme#233]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

最新版开启theme后，文生图预览会受影响，只会显示最后生成的图片，预览图生成过程就失效了

### 🚦 期望结果 | Expected Behavior

因为老版本中未出现该问题，希望尽快修复

### 📷 复现步骤 | Recurrence Steps

关闭theme用原生的则不会出现

**Comment by luuIlee** [comment]
同样的问题,无法看到生成图进度,关闭插件就正常了.
