### ISSUE TITLE
Hello from Cozy Nest

### ISSUE THREAD

**Issue by Nevysha** [lobehub/sd-webui-lobe-theme#237]
Hello ! Looking for a way to get in touch with you. Any discord server maybe ? 
I saw that our project share similarities (and you credited me, lovely ❤️ !) 
Cya
Nevysha

Deepl translate :
你好! 我正试图找到一种方法来联系你。也许有某种 Discord 服务器？
我看到我们的项目有相似之处（而且你已经为我写下了名字，可爱的❤️！） 。
Nevysha

**Comment by FutonGama** [comment]
> ![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/95169493/2eb6b223-1474-4694-a2e8-7bd86b1bfe61)
@Nevysha one of the things i like on your version is your extra network is always on top when you scroll down, i hope @canisminor1990 add that also, your both have done a nice work. So my recommendations for caninsminor1990 for him to improve more on his version is.

Extra network categories always on top
Compact menus like one text line more near to the other
Font size
Hide generation info - for some reason is not included
Save the hud location when you change the size of the preview for example
Improve performance, maximum possible, its a little heavy both interfaces, Nevysha is more heavy in my opinion.
The buttons on left and right to open quick setting and extra network setting is too small, on Nevysha occupied all the screen border, is also better.

And for both of you now, a way to drag and drop the UI menus for change their location. Not sure if this is possible but will be a amazing thing to have. For example i don't like my Style menu on bottom of Prompt text box, i prefer on top of it, so drag and drop will make easy for everyone customize it. I good idea is be able to drag and drop when you hold the left click on top of some menu for 2 sec for example so will unlock to drag. 

Also i have a bug with canisminor1990 for some reason tag autocomplete is not completing when you click on the tag. 

Well i like to use more canisminor1990 interface, in my opinion is more beauty but this its just a preference, maybe your both working together can do something even better, i'm looking foward to it.

**Comment by canisminor1990** [comment]
> Hello ! Looking for a way to get in touch with you. Any discord server maybe ? I saw that our project share similarities (and you credited me, lovely ❤️ !) Cya Nevysha
> 
> Deepl translate : 你好! 我正试图找到一种方法来联系你。也许有某种 Discord 服务器？ 我看到我们的项目有相似之处（而且你已经为我写下了名字，可爱的❤️！） 。 Nevysha


❤️ Nice to meet you too! However, I haven't created a Discord channel yet. But you can find me through my Discord ID: canisminor1990.
