### ISSUE TITLE
[Bug] 在使用双列模式的时候,生成图不显示进度以及实时预览图

### ISSUE THREAD

**Issue by luuIlee** [lobehub/sd-webui-lobe-theme#239]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

在使用双列模式的时候,生成图不显示进度以及实时预览图

### 🚦 期望结果 | Expected Behavior

双列模式是非常好的具有创新的功能,希望能够显示进度以及实时预览图

### 📷 复现步骤 | Recurrence Steps

![Snipaste_2023-07-08_12-01-58](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/34571277/76f289a1-078f-493c-98dc-e9220bf90272)

**Comment by jasoncow007** [comment]
是的确实双列的时候就会如此，我也发现了
