### ISSUE TITLE
[Request] 分列模式Split Previewer 请把小按钮和style放回生成按钮generate旁边去

### ISSUE THREAD

**Issue by xueqing0622** [lobehub/sd-webui-lobe-theme#252]
### 🥰 需求描述 | Feature Description

分列模式Split Previewer 请把小按钮和style放回生成按钮generate旁边去,我不想他占用太多左边我的主工作区间,

### 🧐 解决方案 | Proposed Solution

分列模式Split Previewer 请把小按钮和style放回生成按钮generate旁边去,我不想他占用太多左边我的主工作区间,
![Image text](https://i.imgur.com/XkcLwpo.jpg)

### 📝 补充信息 | Additional Information

谢谢,辛苦了

**Comment by amimi818** [comment]
小按钮等放回右边生成按钮下面也不太好，因为这些小按钮和style都是针对提示词的操作，双列模式下应该和提示词区在一起比较合适，但确实占用了左边很多主工作区，我的建议是把小按钮和style下拉框整合在一行中，参见Issue #191
https://github.com/canisminor1990/sd-webui-lobe-theme/issues/191
