### ISSUE TITLE
[Request] nginx subpath support

### ISSUE THREAD

**Issue by EngsShi** [lobehub/sd-webui-lobe-theme#258]
### 🥰 需求描述 | Feature Description

I have a nginx proxy path is  http://127.0.0.1:8080/subpath/

Now, lobe-theme  is load from root path , have 404 error
```
await fetch('/lobe/package');
```

### 🧐 解决方案 | Proposed Solution

Is it possible to have environment variable options, like sd-webui args  --subpath

like this https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/211c3398f64b56a9297e831f4662b483793760d6

**Comment by geekidentity** [comment]
同样遇到这个问题

**Comment by geekidentity** [comment]
请问这个有修复计划吗
