### ISSUE TITLE
[Bug] 分列模式下，图片预览区，多张结果图片放大浏览时，无法进行图片切换

### ISSUE THREAD

**Issue by amimi818** [lobehub/sd-webui-lobe-theme#260]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

1. 分列模式下，图片预览区，多张结果图片放大浏览时，无法通过翻页箭头进行不同图片切换；
2. 传统模式下，正常

如图：

### 📝 补充信息 | Additional Information

<img width="1918" alt="Image" src="https://github.com/canisminor1990/sd-webui-lobe-theme/assets/133093934/4a623a2e-1c74-47f5-8245-1acdf9647632">

**Comment by bluelovers** [comment]
https://github.com/canisminor1990/sd-webui-lobe-theme/issues/319
