### ISSUE TITLE
[Bug] Open Outpaint extension does not take the whole space.

### ISSUE THREAD

**Issue by Sniper199999** [lobehub/sd-webui-lobe-theme#261]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Firefox

### 🐛 问题描述 | Bug Description

Open Outpaint extension gets bugged and its UI is all messed up. This doe not happen on other UI extensions.

### 🚦 期望结果 | Expected Behavior

Open Outpaint UI gets displayed properly.

**Comment by mnn** [comment]
Not sure if the same issue, but for me OpenOutpaint only spans half a screen, making it hard to use. That's on Vivaldi (Chrome) running on Linux (Manjaro).

<img width="741" alt="2023-08-03_09-12" src="https://github.com/canisminor1990/sd-webui-lobe-theme/assets/1975567/a77e3276-2c34-4993-858a-69b0696b3a07">

Version (from extensions tab): 428b2f4f | Tue Jul 25 08:44:56 2023

**Comment by mnn** [comment]
I have put together a [quick hack](https://userstyles.world/style/11301/sdwu-fix-openoutpaint-size-in-lobe-theme) to improve the size (custom styles, use style extension for browser, e.g. [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)). It's far from perfect, for example you can scroll lower to hide part of the canvas, but scrolling on canvas it taken by OpenOutpaint as brush size change, so you have to scroll on header. But until it's officially fixed we can at least somewhat use the OpenOutpaint.

**Comment by mnn** [comment]
Still broken in 3.0.8.
<img width="755" alt="2023-10-17_08-54" src="https://github.com/lobehub/sd-webui-lobe-theme/assets/1975567/b014fed2-ab13-43bc-8444-c1cb5039fca4">

**Comment by CaptaiNiveau** [comment]
For me it isn't that broken, but the left menu is still covered by the side tab and the background image isn't centered (1/3 on the right is empty)
