### ISSUE TITLE
[Bug] High-res img generation takes much more time if looking at image preview window

### ISSUE THREAD

**Issue by MansTomb** [lobehub/sd-webui-lobe-theme#264]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

When generating high-resolution images (for me is 1524x1524) after all the steps it's stuck on 95% entirely using my GPU. The problem is while I am watching at UI this step can take 2m, but if I am alt-tabbed this step ends in 10 seconds.

Tried to remove some extensions, also tried using the default automatic1111 UI and it works fine. Tried PWA and the default browser, and tried another browser (edge). Nothing helps for now.

### 🚦 期望结果 | Expected Behavior

When generating high-res images while looking at UI must take a similar amount of time as if alt-tabbed.

### 📷 复现步骤 | Recurrence Steps

Start UI, select the high-res image, try to generate without alt-tabbing and generate another one while in alt-tab.

### 📝 补充信息 | Additional Information

1524x1524 also an limit for my GPU (3070) so it takes all my memory at this last step.

UPD: As Kryptonic83 says after some time I also found out that scrolling out of the preview image is making it faster, I also tried disabling GPU acceleration but it doesn't help me.

**Comment by Kryptonic83** [comment]
I noticed with this extension enabled my it/s was slower compared to with it disabled. Then i noticed if i start generating images and click to another browser tab the it/s speeds up in the command prompt, but clicking back to SD tab w/ this extension enabled, the it/s slows down again. This issue does not happen with default Auto1111 w/ Kitchen/Lobe extension disabled. Maybe something with GPU acceleration in the browser slowing it down. (I'm using Edge browser)

**Comment by Kryptonic83** [comment]
Seems to be related to the progress bar. Going into Auto1111 settings > Live previews and unchecking show progressbar helped. Now i don't really see a difference in it/s when looking at image preview vs scrolling down. At the moment I also have show live previews turned off so i'll test with that on too.

**Comment by canisminor1990** [comment]
lobe theme setting - reduce animation

**Comment by Kryptonic83** [comment]
> lobe theme setting - reduce animation

Tried that and it did help a little but what made the biggest difference was hiding the progress bar.

**Comment by FutonGama** [comment]
> this was happen with me even without the extension and i'm saying about that for months already and i have find many people with the same problem. One of this problems is related to process of the windows named "dwm.exe", and xbox game bar screen capturing system. Well i improved ALOT my performance doing a few stuffs on my PC. For example, on windows start menu search for Graphics and go to Graphical elements or something like that. (I'm brazilian so its all in portuguese for me and i don't know how is called in English). So. on this image. 
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/95169493/1e5454ae-84f8-4700-8b70-dc77c20222a8)
I have added cmd.exe, dwm.exe, explorer.exe, my browser also and ctfmon.exe. You need add this EXEs and put for use your graphic card with maximum performance. 
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/95169493/77b6d97a-4544-4b7e-9ba9-436b69ef3598)
Usually this EXEs are located on your Windows folder or Windows/system32 folder. And its mandatory restart computer after or nothing will change. Well it improved alot the freezings looking to the image. Now about my command args i recommend use this commands. --opt-sdp-no-mem-attention --opt-split-attention --opt-channelslast. Will also help alot. 
Here my commands:
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/95169493/9c0d1955-a17d-4034-8f4f-7340b20d1ca4)

I hope something of this help you cause i have search on alot of places about this problem and all this things i have done improved alot it. Ah and firefox is not good to generate images, its more common to take more time when look to images, at least here. With all of this works great here.
