### ISSUE TITLE
[Bug] cursor does not always sit on correct line in positive prompt text box in txt2img, at least

### ISSUE THREAD

**Issue by pmcculler** [lobehub/sd-webui-lobe-theme#265]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

The txt2img positive prompt box sometimes places the cursor on the wrong line, particularly at the end of the prompt. I use prompts over 40 lines, so this might be uncommon, but it makes it difficult to use the edit box on prompts, and that's quite frustrating at times.
Example of buggy behavior: when the cursor is on line 46, and you press 'space', the space is inserted at the correct column position but on line 47, not line 46.
Highlighting gets a bit edgy there too; when you have the cursor on the supposedly second to last line, but you select the text to highlight it, the text that appears in the highlight is the text from the last line.

### 🚦 期望结果 | Expected Behavior

When the cursor is on line 46, for example, and you press 'space', the space should be inserted on line 46, not line 47.

### 📷 复现步骤 | Recurrence Steps

A little tricky to reproduce from first principles, but it looks like having enough lines to scroll the text box plus at least one line that wraps will cause the issue to appear.
1
2
3
4
5
6
7
8
9
0
11
12
13
{|::pgm_fabrics::|::pgm_dresses::|::pgm_flavors::|::pgm_armor::|::pgm_random_material::|::pgm_adjectives:: {2-4$$::pgm_surfaces::}},
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36sss
37

### 📝 补充信息 | Additional Information

I use lots of dynamic prompting, if that helps.

**Comment by ColorfanXP** [comment]
Ive been getting that bug as well. Like Ill be selecting text, but the highlighted part is selecting some "ghost" text. Or the text that is visible is not matching up with the whole text box if I select it all.

**Comment by gurukast** [comment]
same

**Comment by Nagashurai** [comment]
Firefox user here, I noticed that this only seems to occur when the **Prompt Syntax Highlighting** is enabled. After disabling this feature I am able to add as many lines as I would like without having the cursor at a wrong location. Would be nice to see this working, but hopefully this will help pinpoint any troubleshooting of this issue. 

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/15712281/176393ce-b416-498a-96de-5b2c47ae425f)

**Comment by picobyte** [comment]
I have the same, however if I disable syntax highlighting, text is unreadable. Only when I select it it is readable.
