### ISSUE TITLE
[Bug] Theme Settings button doesn't do anything in Vlad's Repo. 

### ISSUE THREAD

**Issue by RaXorX** [lobehub/sd-webui-lobe-theme#286]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

In Vlad's repo cannot access Theme Settings. 

### 🚦 期望结果 | Expected Behavior

Theme Settings should be accessible.

### 📷 复现步骤 | Recurrence Steps

Install extension in Vlad's Repo

**Comment by Bodzijun** [comment]
in my case don't work navigation to  tab 'From Text' on vlad fork

**Comment by RaXorX** [comment]
> in my case don't work navigation to tab 'From Text' on vlad fork

Navigation works but it doesn't update in the bar. Also, I had gotten the settings to display somehow. In the 2.8.1 update it works just fine, in the 2.8.2 and above, it seems a bit different in how the settings is displayed. But even then had gotten it to work once after multiple installs but cannot replicate it again.

**Comment by LindezaBlue** [comment]
I too am experiencing the same issue, also the setting _(the gear button on the top right)_ button crashes the whole interface.

I also am getting this error:
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/141217866/cb4e4788-8c00-405b-b3e9-8a8bd4ca3f28)
