### ISSUE TITLE
[Bug] Mutltiple issues - Blank settings menu - styles issues

### ISSUE THREAD

**Issue by Kalzeroth** [lobehub/sd-webui-lobe-theme#294]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

I have multiple problems, probably all related to the same crash below.

This extension settings/theme menu (at top right) doesn't open => I'm stuck on a blank screen
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/47315219/b44d5ab0-a235-4704-a8f6-69b11874b525)

The positive prompt is black on black.
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/47315219/03c11473-70d2-461f-91cf-1d879fa4124f)

Error in the CMD at `STARTUP` - there is no error when i press the button :

```
Launching Web UI with arguments: --no-half-vae --xformers --theme=dark
*** Error running preload() for C:\Users\Kalzeroth\stable-diffusion-webui\extensions\sd-webui-lobe-theme\preload.py
    Traceback (most recent call last):
      File "C:\Users\Kalzeroth\stable-diffusion-webui\modules\script_loading.py", line 27, in preload_extensions
        module.preload(parser)
      File "C:\Users\Kalzeroth\stable-diffusion-webui\extensions\sd-webui-lobe-theme\preload.py", line 2, in preload
        parser.add_argument(
      File "C:\Users\Kalzeroth\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1441, in add_argument
        return self._add_action(action)
      File "C:\Users\Kalzeroth\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1807, in _add_action
        self._optionals._add_action(action)
      File "C:\Users\Kalzeroth\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1643, in _add_action
        action = super(_ArgumentGroup, self)._add_action(action)
      File "C:\Users\Kalzeroth\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1455, in _add_action
        self._check_conflict(action)
      File "C:\Users\Kalzeroth\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1592, in _check_conflict
        conflict_handler(action, confl_optionals)
      File "C:\Users\Kalzeroth\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1601, in _handle_conflict_error
        raise ArgumentError(action, message % conflict_string)
    argparse.ArgumentError: argument --lobe-debug: conflicting option string: --lobe-debug

---
```

### 📷 复现步骤 | Recurrence Steps

Every startup.

### 📝 补充信息 | Additional Information

On a side-note, the styles box is ugly right not, can you maybe allow this whole div to be resized or at least make the refresh smaller ? 
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/47315219/8487a2ac-28d3-4d4a-8bb0-134c5972823d)

**Comment by Kalzeroth** [comment]
Actually, the error was from the extension I installed from the webui. But since the github recommended to clone this project instead, i had both together - but the other one disabled in extension tab -

I cleaned the extension folder and only have lobe once now.

There is no more error in the CMD, but the issues all remain.

**Comment by procule** [comment]
I also experience the `positive prompt is black on black`
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/152512/765433cc-99dc-4540-a60c-279ffa5aed14)

It looks to be a css issue or maybe coming from another extension...
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/152512/fc8a906f-5909-479b-916e-1faa27af5e1c)

By removing that style `color: transparent`, it resolves the issue.

**Comment by AshtakaOOf** [comment]
I have the same issues, but for now you can `git reset cc48800 --hard` in the lobe folder, this will rollback to an older commit.

**Comment by devilcheng** [comment]
I encountered the same problem, the settings page was blank, and when selecting prompt content with a lot of text, it would display out of position.

**Comment by AshtakaOOf** [comment]
I'm not encountering the issue when doing `git pull` now.
Can anyone else confirm?
