### ISSUE TITLE
[Bug] Theme setting button kills the UI

### ISSUE THREAD

**Issue by devingfx** [lobehub/sd-webui-lobe-theme#297]
### 💻 系统环境 | Operating System

Other Linux

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Since last update, when I click on the theme settings buton (cog icon at top right) the page empties leaving juste background color and nothing more is possible to do but refresh

### 🚦 期望结果 | Expected Behavior

The theme setting popup shows

### 📷 复现步骤 | Recurrence Steps

- click on the top right cog icon
- refresh
- cry loosing your current work and settings

**Comment by hobolyra** [comment]
Same issue, posts this over and over again: (IP removed)
`2023-07-26 12:59:22,255 - _client.py [line:1729] - INFO: HTTP Request: POST http://XXXXX/api/predict "HTTP/1.1 200 OK"`

**Comment by devilcheng** [comment]
I encountered the same problem, the settings page was blank, and when selecting prompt content with a lot of text, it would display out of position.

**Comment by eypacha** [comment]
Same bug here but on Win (chrome,  description,  expected and recurrence are the same)

**Comment by bluelovers** [comment]
https://github.com/canisminor1990/sd-webui-lobe-theme/issues/321
