### ISSUE TITLE
[Question] 装完lobe插件，跑图测试，速度变慢了？跑1girl，150步其他参数为默认

### ISSUE THREAD

**Issue by gtbloody** [lobehub/sd-webui-lobe-theme#298]
### 🧐 问题描述 | Proposed Solution

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/130019359/4b6f22f9-0fdf-4f2f-8307-f1e640432a3a)
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/130019359/1bda79f1-8b5a-4baf-95e9-c7f1febdca23)
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/130019359/7cae0057-46b9-4614-9ff7-cadbdb3265e2)
我的是4090laptop，16g显存64g内存，sd用的秋叶整合包4.2，torch2.0.1+cu118，用同一个模型，跑1girl，150步，其他选项全都默认且一致，好像速度变慢了？

**Comment by gtbloody** [comment]
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/130019359/e817f5e6-5b38-4ff6-ab99-a76ad7121a0f)
补充一下，把lobe的语言设为English后，跑图速度有明显变快一些，但仍然比不上原生ui
原生ui 是20it/s，lobe插件设为中文是11it/s，lobe插件设为英文是15it/s

**Comment by Myoko** [comment]
暂时还是用原生的UI
