### ISSUE TITLE
[Bug] Image Gallery navigation buttons 

### ISSUE THREAD

**Issue by haddadrm** [lobehub/sd-webui-lobe-theme#305]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

Image Gallery navigation buttons do not function in full screen mode.

### 🚦 期望结果 | Expected Behavior

Navigation buttons should allow users to navigate through generated images in full-screen mode.

### 📷 复现步骤 | Recurrence Steps

 Steps to reproduce:

Click twice on a generated image in to get to the full screen (Light Box) mode
Click on Next ">" or Previous "<" buttons
Buttons have no effect, cannot navigate between images

### 📝 补充信息 | Additional Information

![1](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/121486289/1ec511a6-aff9-4063-acce-73a65de6ebdc)
![2](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/121486289/4712c5ca-be43-4642-8664-61c8b568abf0)
![3](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/121486289/a1917f3a-b116-4cf5-84b8-0dccd1dfcb32)

**Comment by Zullian** [comment]
Can confirum bug also image parameters doesn't refresh when clicking/cycling through generated images, SEED number is the same for all of the images when it should be +1 on each

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/3374100/c82b0a1f-e798-470b-b723-8660c2367e37)

**Comment by bluelovers** [comment]
https://github.com/canisminor1990/sd-webui-lobe-theme/issues/319
