### ISSUE TITLE
[Bug] Line breaks when there are too many prompts

### ISSUE THREAD

**Issue by Chunbear** [lobehub/sd-webui-lobe-theme#313]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

Line feed problem when too many prompts are entered in the input box.
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/34836688/cbe5fbaa-16f5-40c1-9cc8-4aadfddc087f)
There will be a discrepancy between the actual word selected and the word displayed.
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/34836688/ccee3325-2b1b-4a3a-abf1-27dcf6d5bc1f)
Manually expanding the input box solves this problem
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/34836688/163eecde-8eb0-47da-b748-c2e3525d53fb)

### 🚦 期望结果 | Expected Behavior

The input box can automatically change with the number of prompt words entered, or to solve the problem of inconsistent display

### 📷 复现步骤 | Recurrence Steps

You can use long promptswords for testing

**Comment by devilcheng** [comment]
I've been having the same issue too. It's been bugging me for a while now. How can I fix this?
