### ISSUE TITLE
[Bug] not support offline use

### ISSUE THREAD

**Issue by bluelovers** [lobehub/sd-webui-lobe-theme#316]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

當網路出現問題 無法連接外網的時候
以內網或者 127.0.0.1 連接都會無限期地停留在讀取畫面
無法完成載入介面

### 🚦 期望结果 | Expected Behavior

不論是否能連接外網都能使用

**Comment by hexive** [comment]
Same issue When no external internet is unavailable I get infinite loading screen.

Steps to reproduce: disable wifi or networking and reload.

Is there an online dependency? Can this run locally without internet?

Thanks!

**Comment by swieder227** [comment]
+1, I'm confused as to why this theme seemingly requires internet. Running with no network connection (i.e. offline) and it hangs on the loading screen `StableDiffusion / LobeTheme is initializing, please wait...`. If I disable `sd-webui-lobe-theme`, then SD starts up as expected even when offline.

**Comment by HikiWaltz** [comment]
Same here... Stuck loading if offline

**Comment by Goldenwolfz21** [comment]
Any fix?
