### ISSUE TITLE
[Bug] saving settings in firefox doesnt work

### ISSUE THREAD

**Issue by moonshinegloss** [lobehub/sd-webui-lobe-theme#326]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Firefox

### 🐛 问题描述 | Bug Description

If I save settings in firefox they get ignored on "apply and restart" but if I do the same in chrome, the settings will be saved and firefox then sees the same changes - but again can't change them unless done in a chrome based browser.

**Comment by Talae06** [comment]
Also using Firefox (but on Windows), not exactly the same problem, but it does take multiple (like between 3-5) tries before the changes are saved. Also only seem to function for one setting at a time. Possible temporary workaround is manually editing lobe_theme_config.json.
