### ISSUE TITLE
[Request] 

### ISSUE THREAD

**Issue by Ageless2016** [lobehub/sd-webui-lobe-theme#331]
### 🥰 需求描述 | Feature Description

1. 希望能够支持设置附加网络内页签的显示顺序（嵌入式->超网络->Lora-...）
2. 希望能够支持按比例设置参数区、出图区的布局比例
3. 希望能够支持检测模型的新版本，并由用户手动确认更新

### 🧐 解决方案 | Proposed Solution

1、在设置/附加网络侧边栏中增加页签显示顺序设置
2、在设置中增加布局设置，支持设置布局比例
3、在附加网络中增加浏览C站模型，并支持下载到本地。后续能够自动检测模型版本，提示更新。

**Comment by misaka15273** [comment]
c站助手可以用吧？
