### ISSUE TITLE
[Bug] sd-webui-supermerger not allow live previews

### ISSUE THREAD

**Issue by soyatlas** [lobehub/sd-webui-lobe-theme#335]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

If I install sd-webui-supermerger extension, then the live previews not happen, only show the final image.

If I remove sd-webui-supermerger extension, then run ok the live previews.

### 🚦 期望结果 | Expected Behavior

See the live previews showing image is maked

### 📷 复现步骤 | Recurrence Steps

Install sd-webui-supermerger extension, then stop the live previews.

### 📝 补充信息 | Additional Information

the extension original site:

https://github.com/hako-mikan/sd-webui-supermerger

Thanks for lobe theme.

**Comment by bourneash** [comment]
I can also confirm the same bug as @soyatlas with sd-webui-supermerger. Disabling the sd-webui-supermerger extension resolves the issue and preview works properly again.
