### ISSUE TITLE
[Bug] lora部分无法加载

### ISSUE THREAD

**Issue by JaysonGeng** [lobehub/sd-webui-lobe-theme#340]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

界面出错，lora部分无法加载
![Snipaste_2023-08-17_14-19-39](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/34483957/4ce2e1f2-99b6-4aa1-9927-173ae4da4c77)

### 📷 复现步骤 | Recurrence Steps

附上所有插件列表
![Snipaste_2023-08-17_14-20-38](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/34483957/1e5fd124-d60f-482e-b501-0e1fdff9b631)
![Snipaste_2023-08-17_14-20-11](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/34483957/69d3ce78-79eb-48ef-8702-623df3a9f2e5)

**Comment by lonelyman0907** [comment]
I have similar problem, my lora only showing partial.

**Comment by whitevamp** [comment]
same issue here.
