### ISSUE TITLE
[Bug] Progressive Web App: Splash screen on start up does not allow user to enter gradio credentials

### ISSUE THREAD

**Issue by rafritts** [lobehub/sd-webui-lobe-theme#341]
### 💻 系统环境 | Operating System

Other Linux

### 🌐 浏览器 | Browser

Chrome

-----

### 🐛 问题描述 | Bug Description

If the webui.sh is launched using `--gradio-auth username:password`, the Lobe splash screen wont allow the user to enter credentials, and the splash screen will never disappear. 

This is specifically a problem with Progressive Web Apps, and how it caches something. If the cache is removed somehow, the functionality is restored as intended. Therefore a simple work around on Desktop is to Ctrl + F5 (hard refresh), but this functionality is broken on mobile. 

もし webui.sh が --gradio-auth username:password を使って起動された場合、Lobeのスプラッシュ画面はユーザーが認証情報を入力することを許可せず、スプラッシュ画面は消えることがありません。

これは、プログレッシブウェブアプリと、何かをキャッシュする方法との具体的な問題です。キャッシュが何らかの方法で削除されると、機能が意図した通りに復元されます。したがって、デスクトップ上での単純な回避策はCtrl + F5（ハードリフレッシュ）ですが、この機能はモバイル上で壊れています。

このテキストはGPT-4を使用して翻訳されました。

-----

### 🚦 期望结果 | Expected Behavior

The splash screen resolves to the gradio login page, to allow users to enter credentials. 

スプラッシュ画面は、ユーザーが認証情報を入力できるように、gradioのログインページに解決します。

-----

### 📷 复现步骤 | Recurrence Steps

Install the app previously using PWA.  Launch the webui.sh with the flags `--gradio-auth username:password`. Try to access A1111.  It might work the first time if it is not cached.

PWAを使用して事前にアプリをインストールします。フラグ --gradio-auth username:password で webui.sh を起動します。A1111にアクセスしてみてください。ページがキャッシュされていない場合、ログイン機能は最初の時間に期待通りに動作するかもしれません。

-----

**Comment by BaiterYamato** [comment]
same here
