### ISSUE TITLE
Scrolling doesn't work on Vivaldi [Bug] 

### ISSUE THREAD

**Issue by Eluvade** [lobehub/sd-webui-lobe-theme#342]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Other

### 🐛 问题描述 | Bug Description

Inability to scroll.

### 🚦 期望结果 | Expected Behavior

Mouse wheel is supposed to scroll through the content of the page.

### 📷 复现步骤 | Recurrence Steps

Fresh installation of the Automatic1111 extension in the Vivaldi browser.

### 📝 补充信息 | Additional Information

I've locally fixed this issue by adding the following css code:
```css
gradio-app {
  overflow-y: scroll;
}
```

**Comment by Eluvade** [comment]
I'd make a PR to fix it, but my solution probably isn't optimal, but merely a hack, since I'm unaware how gradio works

**Comment by ArturFormella** [comment]
The same in Firefox
