### ISSUE TITLE
[Bug] UI breaks in WebUI1.6.0

### ISSUE THREAD

**Issue by SLAPaper** [lobehub/sd-webui-lobe-theme#350]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

After upgraded to v1.6.0,
1. the extra networks sidebar is broken (it's move to tabs in original UI)
2. the generation result is placing at wrong position
3. the quick settings button in left sidebar is misplaces if default width set to ~370 pixels and below 

### 📝 补充信息 | Additional Information

Update: Workaround of problem 2 and 3 by using tampermonkey:
https://gist.github.com/SLAPaper/080f93885dcd7ae8ba414dc5c576652f

or GreasyFork link: https://greasyfork.org/zh-CN/scripts/474294-a1111-webui-fix-lobe-theme

**Comment by RunawayOrange** [comment]
the Same issues

**Comment by meegle84** [comment]
same in macos ventura, brave browser

**Comment by ColorfanXP** [comment]
Not to mention text input is really weird. Like theres phantom text behind the cursor.

**Comment by SLAPaper** [comment]
I workaround problem 2 and 3 by using tampermonkey:
https://gist.github.com/SLAPaper/080f93885dcd7ae8ba414dc5c576652f

**Comment by dexyel** [comment]
It's not a bug. WebUI 1.6.0 has different UI layout than 1.5.2 with new dropdowns and a draggable handle between the settings and the generation. Lobe "just" needs an update to suit the new layout. Besides, it's still the RC, at least wait for the official release.

**Comment by angelineage** [comment]
the Same issues

**Comment by Talae06** [comment]
> I workaround problem 2 and 3 by using tampermonkey: https://gist.github.com/SLAPaper/080f93885dcd7ae8ba414dc5c576652f

Would love to know where one is supposed to put this code :) Thanks in advance !

**Comment by SLAPaper** [comment]
> > I workaround problem 2 and 3 by using tampermonkey: https://gist.github.com/SLAPaper/080f93885dcd7ae8ba414dc5c576652f
> 
> Would love to know where one is supposed to put this code :) Thanks in advance !

@Talae06 It is a User Script, you can use a corresponding extension according to your web browser to load it.
Or look at GreasyFork for finer guide of using User Scripts: https://greasyfork.org/zh-CN/scripts/474294-a1111-webui-fix-lobe-theme
