### ISSUE TITLE
[Bug] Prompt 语法高亮与stable-diffusion-webui-localization-zh_Hans语言包有冲突

### ISSUE THREAD

**Issue by PTALTS-LK** [lobehub/sd-webui-lobe-theme#355]
### 💻 系统环境 | Operating System

Other Linux

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

输入nature(或者其他有翻译的字段)时会变成语言包中的翻译
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/62936489/298881a2-9ea8-47a2-ae2c-82e8955a2dea)
且渲染错误
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/62936489/71a8eeb7-2522-4a32-87e4-f3f8a17feda9)
关闭语法高亮后正常
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/62936489/67756205-3d17-4f24-882b-245430dcc112)

### 🚦 期望结果 | Expected Behavior

只应显示用户输入的原文

### 📷 复现步骤 | Recurrence Steps

1.安装stable-diffusion-webui-localization-zh_Hans语言包
2.设置webui的本地化为zh_Hans(Testing)
3.打开Lobe的Prompt语法高亮功能并重载ui
4.输入```masterpiece, (best quality), 1girl with hair ornament and yellow hair, sunlight, forest, nature,```到正面tag输入框中
5.触发错误

### 📝 补充信息 | Additional Information

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/62936489/aeb12cbf-4ad2-400b-8230-c526f865aa39)

使用Arch linux

lobe commit 41cc9080f727df03198aa273a28ff1a1aa7f1d16

语言包:https://github.com/hanamizuki-ai/stable-diffusion-webui-localization-zh_Hans

**Comment by bluelovers** [comment]
安裝這個 
https://github.com/bluelovers/stable-diffusion-webui-localization-zh_Hant

然後語言包設定裡面選擇 `zh_Hans` (請注意 zh_Hans 與 zh-Hans 的分別)

**Comment by PTALTS-LK** [comment]
> 安裝這個 https://github.com/bluelovers/stable-diffusion-webui-localization-zh_Hant
> 
> 然後語言包設定裡面選擇 `zh_Hans` (請注意 zh_Hans 與 zh-Hans 的分別)

兄啊，你这语言包是繁体硬转简的罢）
看着太别扭了
