### ISSUE TITLE
[Request]1.60正式版已出，期待适配！ 

### ISSUE THREAD

**Issue by jinjin327** [lobehub/sd-webui-lobe-theme#358]
### 🥰 需求描述 | Feature Description

1.60正式版已出，期待适配！ 

### 🧐 解决方案 | Proposed Solution

stable-diffusion-webui界面改动来了很多，现在的主题不适配了

**Comment by canisminor1990** [comment]
⚠️⚠️⚠️ Lobe Theme v3 is compatible with SD WebUI v1.6 and is not backwards compatible. Versions below < 1.6 should be moved to the branch legacy-sd-webui-1.5

Currently, it can run normally with the default configuration, but there are still some minor styling issues that need to be fixed.
