### ISSUE TITLE
[Question] 无法把webUI的启动主题默认为亮色

### ISSUE THREAD

**Issue by H1127** [lobehub/sd-webui-lobe-theme#360]
### 🧐 问题描述 | Proposed Solution

如题，无法把webUI的启动主题默认为亮色，我在webui.bat里添加了“set COMMANDLINE_ARGS= --theme=light”也还是会以黑色主题启动

**Comment by SpenserCai** [comment]
无痕浏览试试看

**Comment by SpenserCai** [comment]
不行的话删掉ui-config.json
