### ISSUE TITLE
[Question] Prompt template cannot input to the prompt bar 提示詞模板載入鍵消失

### ISSUE THREAD

**Issue by lonelyman0907** [lobehub/sd-webui-lobe-theme#374]
### 🧐 问题描述 | Proposed Solution

My UI(only 3 buttons below generate button):
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/114672437/df19bfe1-6d0c-4b87-a9ef-14a8b1861dea)

Official UI(6 buttons below generate button):
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/114672437/94332c5e-3be8-47b2-aa1e-6eb745ff2260)

Where can I get back those buttons?
我要怎麼設定成完整的按鈕?

**Comment by canisminor1990** [comment]
sd webui 1.6 之后按钮就减少了
