### ISSUE TITLE
[Bug] last update -b32ed760- broke the theme

### ISSUE THREAD

**Issue by elpuertorro** [lobehub/sd-webui-lobe-theme#379]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Other

### 🐛 问题描述 | Bug Description

did an update check and there was an update applied and it broke the theme, tried on Firefox and also Edge

### 🚦 期望结果 | Expected Behavior

should have just updated and worked

### 📷 复现步骤 | Recurrence Steps

Go to extensions, check for updates, apply and restart, then just applies local theme like gradio.
<img width="1511" alt="Screenshot 2023-09-04 071003 for lobe team" src="https://github.com/lobehub/sd-webui-lobe-theme/assets/89438466/9512e68c-f2b3-4aa3-8805-d305ed8f973f">

### 📝 补充信息 | Additional Information

I also tried the legacy Kitchen theme and that one works, I am on the SD  DirectML branch if it makes any difference

**Comment by inverherive** [comment]
Same issue with standard SD branch:
version: [v1.6.0] •  python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2
