### ISSUE TITLE
[Question] 多了4行空的

### ISSUE THREAD

**Issue by bj803** [lobehub/sd-webui-lobe-theme#383]
### 🧐 问题描述 | Proposed Solution

不知为什么加载后UI多了4行空的

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/109253859/c7e8c541-b0b0-4507-9b28-b59727406968)

### 📝 补充信息 | Additional Information

不用lobe-theme就正常，不会多4行空的出来。

**Comment by canisminor1990** [comment]
fix in https://github.com/lobehub/sd-webui-lobe-theme/commit/b630d9b0db38e0df8f40bbadad8686c362732749
