### ISSUE TITLE
[Bug] civitai helper在theme更新至3.0.3后无法激活四个图标

### ISSUE THREAD

**Issue by Array-Cats** [lobehub/sd-webui-lobe-theme#384]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

升级到 commits 7365559 （ver.3.0.3）后civitai helper的4个图标无法显示（不管是原版helper的叶小猴修复版还是其他原先可用的fork版），切换至原版UI能够正常显示。

### 🚦 期望结果 | Expected Behavior

helper图标能够正常显示

### 📝 补充信息 | Additional Information

印象中至少到ver.3.0.0的时候还是可以正常显示的

**Comment by bluelovers** [comment]
試試
https://github.com/lobehub/sd-webui-lobe-theme/pull/389#issuecomment-1707564016

**Comment by Array-Cats** [comment]
> 試試 [#389 (comment)](https://github.com/lobehub/sd-webui-lobe-theme/pull/389#issuecomment-1707564016)

经测试功能恢复（基于原版helper的叶小猴修复版）

**Comment by bluelovers** [comment]
> > 試試 [#389 (comment)](https://github.com/lobehub/sd-webui-lobe-theme/pull/389#issuecomment-1707564016)
> 
> 经测试功能恢复（基于原版helper的叶小猴修复版）


話說 這個跟原版有什麼差別?

**Comment by Array-Cats** [comment]
> > > 試試 [#389 (comment)](https://github.com/lobehub/sd-webui-lobe-theme/pull/389#issuecomment-1707564016)
> > 
> > 
> > 经测试功能恢复（基于原版helper的叶小猴修复版）
> 
> 話說 這個跟原版有什麼差別?

你是指我说的helper的差别还是你修正后theme的差别？

**Comment by bluelovers** [comment]
> > > > 試試 [#389 (comment)](https://github.com/lobehub/sd-webui-lobe-theme/pull/389#issuecomment-1707564016)
> > > 
> > > 
> > > 经测试功能恢复（基于原版helper的叶小猴修复版）
> > 
> > 
> > 話說 這個跟原版有什麼差別?
> 
> 你是指我说的helper的差别还是你修正后theme的差别？

helper

**Comment by Array-Cats** [comment]
> > > > > 試試 [#389 (comment)](https://github.com/lobehub/sd-webui-lobe-theme/pull/389#issuecomment-1707564016)
> > > > 
> > > > 
> > > > 经测试功能恢复（基于原版helper的叶小猴修复版）
> > > 
> > > 
> > > 話說 這個跟原版有什麼差別?
> > 
> > 
> > 你是指我说的helper的差别还是你修正后theme的差别？
> 
> helper

没啥明显的区别，up叶小猴也就只是修复了SD 1.5.1后原版helper不能显示4个图标的问题，其余未作改动
