### ISSUE TITLE
[Bug] Non-stop Javascript exceptions in browser

### ISSUE THREAD

**Issue by wywywywy** [lobehub/sd-webui-lobe-theme#386]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

The `main.js` of Lobe generates one exception error a second, as can be seen from the dev console.

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/19997747/fc67d71b-e65e-4522-b73b-424a48dcbab7)

```
main.js?1693833289.7170026:1672 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at main.js?1693833289.7170026:1672:1919
    at main.js?1693833289.7170026:1672:2763
```

It points to this line:
```
                                const e = c.querySelector("br");
```

### 🚦 期望结果 | Expected Behavior

There should be no errors.

### 📷 复现步骤 | Recurrence Steps

No action needed. Errors start as soon as loading starts.

### 📝 补充信息 | Additional Information

NA

**Comment by bluelovers** [comment]
https://github.com/lobehub/sd-webui-lobe-theme/pull/389
