### ISSUE TITLE
Comfyui webui extension panel don't load with lobehub extension activated[Bug] 

### ISSUE THREAD

**Issue by kakachiex2** [lobehub/sd-webui-lobe-theme#387]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

Wen loading the **Comfyui webui extension** with the lobehub extension activated the extension panel doesn't load and I' have to deactivated the lobehud extension and them it works.

### 🚦 期望结果 | Expected Behavior

It's supposed to load correctly in an extra tab.

### 📷 复现步骤 | Recurrence Steps

- Intall Comfyui extension from the extension panel with the lobehub already activated
- Restart the ui and apply change
- In the Comfyui panel click install comfyui and wait 
- them way for the behavior.

**Comment by Sostay** [comment]
这个是没有计划修吗~ 几个月了现在好像还是一样的问题……
