### ISSUE TITLE
[Bug] 与bmab插件存在冲突

### ISSUE THREAD

**Issue by anne43983959** [lobehub/sd-webui-lobe-theme#390]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

当启用[bmab](https://github.com/portu-sim/sd-webui-bmab)插件时，整个lobe theme都会失效，控制台没有任何报错，页面也没有任何报错，虽然这可能应该由bmab插件的作者来解决冲突的问题，但我依然将这个bug反馈出来，因为这并不是某个单一页面元素或者组件出现的问题，而是整个插件在没有任何提示的情况下完全失效

### 🚦 期望结果 | Expected Behavior

不祈求能彻底解决二者冲突的问题，但希望能确认是什么原因导致在无报错的情况下引起整个插件的失效

### 📷 复现步骤 | Recurrence Steps

使用`git clone https://github.com/portu-sim/sd-webui-bmab`安装bmab插件，保持二者都开启的状况下重启控制台，此时lobe失效，关闭bmab插件，再次重启控制台，lobe插件恢复

**Comment by bluelovers** [comment]
https://github.com/portu-sim/sd-webui-bmab/pull/1

**Comment by portu-sim** [comment]
Thank you, anne43983959.
