### ISSUE TITLE
[Bug] Textual Inversion not displaying correctly in the Extra Network tab

### ISSUE THREAD

**Issue by dexyel** [lobehub/sd-webui-lobe-theme#395]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

The gap between the rows of Textual Inversion is too big. But doesn't happen in the other tabs for some reason.

### 📝 补充信息 | Additional Information

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/39320381/a762d311-c74a-4702-8efc-44839a16c866)

**Comment by canisminor1990** [comment]
fix in https://github.com/lobehub/sd-webui-lobe-theme/pull/396
