### ISSUE TITLE
[Bug] 附加网络界面模型一直加载中

### ISSUE THREAD

**Issue by jinjin327** [lobehub/sd-webui-lobe-theme#398]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

3.03版本附加啊网络界面模型一直在加载中。。

**Comment by mccabedd** [comment]
Same here. Chrome Browser.

**Comment by LianmingW** [comment]
Same issue here, infinitely loading. Chrome browser. 
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/32531235/e284e622-90e8-4403-9e40-0cd2db2280f7)
No error in the SD console, in the browser console I saw below, not sure if it has anything to do with Lobe theme.
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/32531235/49385cfb-e3d2-4b5e-91e8-0d90da825ef2)
And If I refresh the browser after the first load, the lora wouldn't even appear anymore.
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/32531235/02cfe2e7-ed13-4d4d-8338-1b2704a31010)
