### ISSUE TITLE
[Request] 自定义浏览器tab的icon和title，以及自定义加载界面logo

### ISSUE THREAD

**Issue by wlchn** [lobehub/sd-webui-lobe-theme#401]
### 🥰 需求描述 | Feature Description

1.能否支持自定义浏览器tab的icon和title，如下图
<img width="104" alt="image" src="https://github.com/lobehub/sd-webui-lobe-theme/assets/4652410/a38b6b91-a3d8-4624-8c1a-d6d1fff93943">

2.加载页面自定义，目前自定义logo后，还是会先出来默认lobe的加载，再出现自定义logo的加载。
<img width="346" alt="image" src="https://github.com/lobehub/sd-webui-lobe-theme/assets/4652410/adde1464-71f5-4cc6-9947-6b63180b288e">

### 🧐 解决方案 | Proposed Solution

如上

**Comment by kakachiex2** [comment]
This happens to me when I'm offline, try to connect to the internet.

**Comment by kakachiex2** [comment]
If this is because is trying to load something from internet maybe the logo, the pint is how I' load a logo locally in my computer

**Comment by AlexanderDash** [comment]
I also want to customize the webpage title and logo
