### ISSUE TITLE
[Bug] 模型加载错误

### ISSUE THREAD

**Issue by Tiktok-T** [lobehub/sd-webui-lobe-theme#408]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 📦 SD Wbui 版本或提交 | Version or Commit

1.6.0

### 📦 Lobe Theme 版本或提交 | Version or Commit

3.0.4

### 🐛 问题描述 | Bug Description

![微信截图_20230911111840](https://github.com/lobehub/sd-webui-lobe-theme/assets/128903556/5cf72834-562b-4b03-bbc6-e74e85b814db)
进入界面模型经常加载不出或一直显示时间载入信息（能正常切换模型），需要刷新页面或者重新启动webui才有机率正常，经常需要刷新三次或以上。

**Comment by canisminor1990** [comment]
排查方法，将 webui 和 lobe theme 更新到最新，如果依然有问题，尝试排查↓是否和其他插件存在冲突

**Comment by canisminor1990** [comment]
https://github.com/lobehub/sd-webui-lobe-theme/issues/410
