### ISSUE TITLE
[Bug] Folder empty message when incompatible with current Base Model of checkpoint

### ISSUE THREAD

**Issue by BlafKing** [lobehub/sd-webui-lobe-theme#420]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 📦 SD Wbui 版本或提交 | Version or Commit

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4

### 📦 Lobe Theme 版本或提交 | Version or Commit

https://github.com/lobehub/sd-webui-lobe-theme/commit/22162d97313a751a6a24aaadd2e6bbcf069459ea

### 🐛 问题描述 | Bug Description

When SDXL 1.0 is selected, it doesn't list any models incompatible with SDXL 1.0
So my Textual Inversions for example, do not get listed when a SDXL 1.0 checkpoint is being used.

The current description is quite confusing, since it states that nothing is in the folder, instead of explaining to the user that no compatible models for SDXL 1.0 are found.

I think it would be a lot clearer if the info displayed correctly states that the folder isn't empty, but nothing shows up because nothing is compatible with SDXL 1.0, for me this was really confusing:

SDXL 1.0 Base selected:
![2023-09-19 04_48_41](https://github.com/lobehub/sd-webui-lobe-theme/assets/9644716/ee39f4c7-d2ed-48b0-873e-c689023fcf32)

### 🚦 期望结果 | Expected Behavior

I'm not exactly sure what the best solution would be, 
Maybe a check could be done to see if the folders contain any models and change the message according to the presence of models in the folder?

For example if models are found but Automatic1111 has no available models to select a message like this could be shown:
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/9644716/31e03a58-6971-4bea-8632-ad218282e43e)

Otherwise maybe the easiest solution is to change the message all together to something more general like:
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/9644716/2f8a61d9-26fa-4cfb-93b9-181b33e0d1bf)

Anything that would indicate to the user that the current Base Model of the Checkpoint is causing the model selection window to be empty, not because of an empty folder.

### 📷 复现步骤 | Recurrence Steps

1. Select a checkpoint with base model SDXL 1.0
2. Have no compatible models with SDXL 1.0 in a directory
3. Folder empty message pops up while folder isn't empty

### 📝 补充信息 | Additional Information

OS: Windows 10 22H2
Python: 3.10.6
Browser: Brave v1.58.127

**Comment by canisminor1990** [comment]
These empty messages are provided by default by the sd webui, you can try providing feedback to the webui repository issues.

**Comment by BlafKing** [comment]
Thanks for letting me know!
I'll provide the suggestion there instead 👍🏻
