### ISSUE TITLE
[Bug] UI显示错误，默认的单页分栏变成双页分栏。

### ISSUE THREAD

**Issue by LiarMTTT** [lobehub/sd-webui-lobe-theme#424]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

UI显示错误，非常影响使用体验。
发生过程：启动Stbble Diffusion web UI后，UI载入后第一秒是正常的界面，然后下一秒就会变成下面这样，从一页分栏变成了两页分栏，一开始以为是UI设置的问题，反复检查和尝试之后感觉不是设置问题。
请问是bug还是什么原因？
The UI displays errors, which greatly affects the user experience.
Occurrence process: After starting the Stbble Diffusion web UI, the first second after the UI is loaded is the normal interface, and then the next second it will change to the following, from one page with columns to two pages with columns, which I thought at first There is a problem with the UI settings. After repeated checks and attempts, I feel that it is not a setting problem.
Is it a bug or something else?
![5TBE_6{Q$PT~1XX3 UI显示错误，非常影响使用体验。
发生过程：启动Stbble Diffusion web UI后，UI载入后第一秒是正常的界面，然后下一秒就会变成下面这样，一开始以为是UI设置的问题，反复检查和尝试之后感觉不是设置问题。
~$}Q](https://github.com/lobehub/lobe-chat/assets/70681116/e1e1ecfd-263e-4a14-a5c6-3a1f24ed434e)

### 🚦 期望结果 | Expected Behavior

如果是bug，希望修复，如果是其他原因，请告知解决方法。
If it is a bug, I hope it will be fixed. If it is for other reasons, please tell me the solution.

### 📷 复现步骤 | Recurrence Steps

正常的使用web UI的拓展>可下载＆扩展>从网址安装插件进行安装，两个方法都尝试过。
Normally use the extension of the web UI > Downloadable & Extension > Install the plug-in from the URL to install it. I have tried both methods.

### 📝 补充信息 | Additional Information

尝试过切换版本，7月17的0eab3e0~最新的ea6000a4版本，都依旧存在UI问题。
I have tried switching versions, from 0eab3e0 on July 17 to the latest ea6000a4 version, but there are still UI problems.

**Comment by LiarMTTT** [comment]
关闭除了lobe以外的插件后重启Stbble Diffusion问题依旧存在，如图。
After closing plug-ins other than lobe and restarting Stbble Diffusion, the problem still exists, as shown in the figure.
![6XV1){@PM}$}0VCKG~VX({I](https://github.com/lobehub/sd-webui-lobe-theme/assets/70681116/168df0a7-9d3c-4e6a-938f-c631e0d6bdb7)
![XIL`H7)3R4QDM8A_~D}J4FS](https://github.com/lobehub/sd-webui-lobe-theme/assets/70681116/eb5c738f-7eb3-42bc-919f-606a65683ffb)

**Comment by LiarMTTT** [comment]
顺带一提，还有一个非常影响使用的UI问题，编辑提示词时光标显示不正确（错位）,还有框选时错位。
By the way, there is another UI problem that greatly affects the use. The cursor is incorrectly displayed (dislocated) when editing prompt words, and there is also a misalignment when selecting boxes.
打个比方，我想从platform_heels,cyberpunk city,中间的逗号（,）开始编辑，按下退格键后删除的不是逗号（,）而是f。
For example, I want to edit platform_heels, cyberpunk city, starting from the comma (,) in the middle. After pressing the backspace key, what is deleted is not the comma (,) but f.
![{UPJWNGE4$0_7T QQNOA1M](https://github.com/lobehub/sd-webui-lobe-theme/assets/70681116/309d8980-c429-452b-aaee-cd9fb71f2d92)
![7%TJX7`R8{9N@3HIDZFS5$K](https://github.com/lobehub/sd-webui-lobe-theme/assets/70681116/d708b002-a71b-4038-8aae-743339f4446c)
第二个例子，我需要在cg这个关键词的后方才能选中cg。
In the second example, I need to be behind the keyword cg to select cg.
![~ZWLKW%T$78ATL04 3U1ES](https://github.com/lobehub/sd-webui-lobe-theme/assets/70681116/4997baba-c6c3-43d6-a3c0-9fbb1cfab46b)
第三个例子，当选中跨行提示词的时候错位的问题就体现的很明显了，换行之前是完全没有输入空格的。
In the third example, when the cross-line prompt word is selected, the problem of misalignment is obvious. There is no space at all before the line break.
![O7FT1Y7TX2XDH}LLQ_Z8Z2D](https://github.com/lobehub/sd-webui-lobe-theme/assets/70681116/ab97bb92-0493-45e1-8b2a-d3a94b020361)
4c247)

**Comment by canisminor1990** [comment]
通过你的截图我发现你使用的是dev分支的 lobe theme 请切回主分支 ，那个已经是历史分支

**Comment by LiarMTTT** [comment]
好吧🤣，不知道为什么，WebUI的搜索安装和克隆仓库都是默认下载的2.8.3的版本，手动下载安装3.0.8后就没问题了。
Okay🤣, I don’t know why, the search installation and clone repository of WebUI both download version 2.8.3 by default. After manually downloading and installing 3.0.8, there will be no problem.
