### ISSUE TITLE
[Bug] 和任意汉化插件或汉化配置文件冲突

### ISSUE THREAD

**Issue by yuno779** [lobehub/sd-webui-lobe-theme#439]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 📦 SD Wbui 版本或提交 | Version or Commit

V1.6.0

### 📦 Lobe Theme 版本或提交 | Version or Commit

V3.0.8

### 🐛 问题描述 | Bug Description

![025e2c3caab60bfb09a213212c3f1fb2](https://github.com/lobehub/sd-webui-lobe-theme/assets/131428984/97f1b073-f1bc-4c66-baa6-90b2efa53a22)
![552149d86a5ace90de41134c95e9f294](https://github.com/lobehub/sd-webui-lobe-theme/assets/131428984/90737010-1213-4e85-a71b-9043956c8e5c)
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/131428984/8846c62f-fe2e-4aeb-ac98-3f20e8da7c7b)
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/131428984/e62c0742-3fea-4fdb-b857-514437bb3e6b)
键入的提示词会被翻译成中文，导致光标位置和实际显示的位置不对应，这会影响正常的修改提示词
使用纯英文或者SDWebui原本的主题就没有这个问题
![8ced20c00ccdbe98960eede895e0fc35](https://github.com/lobehub/sd-webui-lobe-theme/assets/131428984/0d3c6bad-e7ca-449b-a0de-2bc42a3d64a8)

**Comment by canisminor1990** [comment]
目前没有找到很好的方法解决这个问题，可以先关闭提示词高亮
