### ISSUE TITLE
[Bug] Prompt Section with wrong highlights

### ISSUE THREAD

**Issue by ExperienceRO** [lobehub/sd-webui-lobe-theme#449]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Microsoft Edge
Ver. 118.0.2088.69 (Compilação oficial) (64 bits)

### 📦 SD Wbui 版本或提交 | Version or Commit

 v1.6.0 - https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4

### 📦 Lobe Theme 版本或提交 | Version or Commit

51acc6e7

### 🐛 问题描述 | Bug Description

![Captura de tela 2023-10-26 093636](https://github.com/lobehub/sd-webui-lobe-theme/assets/15870039/afbbed13-1ef9-4bbf-9fcf-8da9b52c8bfd)

Whenever you need to select a part of the prompt, the part you're selecting is never the actual part being selected, because the highlighting is all wrong.

![Captura de tela 2023-10-26 094201](https://github.com/lobehub/sd-webui-lobe-theme/assets/15870039/20eb0900-e695-46ca-8792-4c5a4fd194cb)

![Captura de tela 2023-10-26 094147](https://github.com/lobehub/sd-webui-lobe-theme/assets/15870039/52097d33-16f3-4a1f-b377-a3724be63f4c)

### 🚦 期望结果 | Expected Behavior

When you select a part of the promtp, this is the part that should be selected.

### 📷 复现步骤 | Recurrence Steps

Typing prompts and then selecting a part of the prompt to correct or delete or whatever.

**Comment by ExperienceRO** [comment]
Exactly!! In the example below, I've skipped a line, so the text is actually at the bottom and there's nothing on the top line where the highlight is.
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/15870039/01503647-c923-4682-989b-780806083ecb)

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/15870039/f3d5f8a1-c310-48a5-a01f-80851efb3d6a)

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/15870039/5541562d-b42e-41b0-be3a-d1cf46161c5c)



> The bug description is very vague, but if this is the same issue I'm having, I can add some additional information:
> 
> For the following scenarios make sure **Prompt Syntax Highlighting** is turned on.
> 
> ### Scenario 1:
> Add the following text (without quotes) into positive prompt and double click on middle of **text2**: "text1, text2, text3" **Expected behavior**: **"text2"** is highlighted. **Actual behavior**: **"text2"** is highlighted, so it works as intended. ![image](https://user-images.githubusercontent.com/18469119/281827009-3b095c02-a36b-45d7-89ad-a0b0b859cd99.png)
> 
> ### Scenario 2:
> Make sure there is no text in the positive prompt, than add the following text and try to select **text2**: " text1, text2, text3" Notice that the text starts with two spaces. **Expected behavior**: **"text2"** is highlighted. **Actual behavior**: **", tex"** is highlighted. Also the two spaces at the beginning of the text are not shown. ![image](https://user-images.githubusercontent.com/18469119/281827135-50620b47-d1a3-48d6-af9a-dc17a479de25.png) **NOTE:** in the above image the text is selected by click and drag; if the text is selected by double-click than it looks like this: ![image](https://user-images.githubusercontent.com/18469119/281827844-2e4407d4-b540-49db-84b9-124cf6c2a78c.png)

**Comment by Mozoloa** [comment]
I can add to this, it looks like it's not taking the formatting into account somehow

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/20817233/63ec425f-034c-4299-b6b0-5c3f63cde762)

**Comment by Mozoloa** [comment]
I can add to this, it looks like it's not taking the formatting into account


https://github.com/lobehub/sd-webui-lobe-theme/assets/20817233/1393eaa4-b03a-4b24-9547-266a587ecd1a
