### ISSUE TITLE
[Bug] 生成信息取代功能有bug

### ISSUE THREAD

**Issue by anne43983959** [lobehub/sd-webui-lobe-theme#474]
### 👀 检查清单 | Initial checklist

- [X] 已经阅读了 [常见问题](https://github.com/lobehub/sd-webui-lobe-theme/issues/467) | I have read the [FAQ](https://github.com/lobehub/sd-webui-lobe-theme/issues/468)
- [X] 插件和 SD WebUI 均为为最新版本 | Plugin and SD WebUI both are the latest version
- [X] 插件的分支为 main | The branch of the plugin is main
- [X] 在单独开启插件的情况下，问题仍然存在 | The problem still exists when the plugin is turned on separately

### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 📦 SD Wbui 版本或提交 | Version or Commit

v1.6.0-400-gf0f100e6

### 📦 Lobe Theme 版本或提交 | Version or Commit

c9c1bf51

### 🐛 问题描述 | Bug Description

开启生成信息替代以后，点击重新加载WebUI，会导致该功能失效，并让整个生成信息窗口异常不显示
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/115604775/a8afca0f-9aab-4b5d-9f01-3ab54fec2610)

**Comment by anne43983959** [comment]
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/115604775/85f60e22-baab-4544-8530-e68e4e27ecf7)
另外在不填入任何正面提示词的时候信息分类会发生错误

**Comment by canisminor1990** [comment]
点击重新加载WebUI，会导致该功能失效 这个具体演示有么

**Comment by Amazon90** [comment]
我遇到了相同的問題，在重新載入WebUI后圖片資訊不顯示。
![20231129162958](https://github.com/lobehub/sd-webui-lobe-theme/assets/72290820/90280b01-4fc5-471f-8213-b071174ddf8d)

**Comment by canisminor1990** [comment]
试试更新后是否解决

**Comment by Amazon90** [comment]
> 试试更新后是否解决

測試過了，依然無效，即時關閉了其他主題，使用lobe單一主題，在局部重繪下的圖片資訊始終和我此前發的截圖一樣。

**Comment by canisminor1990** [comment]
> > 试试更新后是否解决
> 
> 測試過了，依然無效，即時關閉了其他主題，使用lobe單一主題，在局部重繪下的圖片資訊始終和我此前發的截圖一樣。

局部重绘以外的场景正常么

**Comment by Amazon90** [comment]
> > > 试试更新后是否解决
> > 
> > 測試過了，依然無效，即時關閉了其他主題，使用lobe單一主題，在局部重繪下的圖片資訊始終和我此前發的截圖一樣。
> 
> 局部重绘以外的场景正常么

都不起效果，文生圖，圖生圖都不行。

**Comment by canisminor1990** [comment]
@anne43983959 @Amazon90 抱歉，我终于发现此 bug 的原因，已经修复
