### ISSUE TITLE
[Bug] Prompt highlighting在安裝Catppuccin theme下無法生效

### ISSUE THREAD

**Issue by Amazon90** [lobehub/sd-webui-lobe-theme#476]
### 👀 检查清单 | Initial checklist

- [X] 已经阅读了 [常见问题](https://github.com/lobehub/sd-webui-lobe-theme/issues/467) | I have read the [FAQ](https://github.com/lobehub/sd-webui-lobe-theme/issues/468)
- [X] 插件和 SD WebUI 均为为最新版本 | Plugin and SD WebUI both are the latest version
- [X] 插件的分支为 main | The branch of the plugin is main
- [X] 在单独开启插件的情况下，问题仍然存在 | The problem still exists when the plugin is turned on separately

### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 📦 SD Wbui 版本或提交 | Version or Commit

v1.6.0-2

### 📦 Lobe Theme 版本或提交 | Version or Commit

v3.2.2

### 🐛 问题描述 | Bug Description

![20231129160234](https://github.com/lobehub/sd-webui-lobe-theme/assets/72290820/de03c6bb-c164-4112-910b-fb50d29a7dd5)
![20231129160453](https://github.com/lobehub/sd-webui-lobe-theme/assets/72290820/39ef411d-2f99-4608-84f2-411432df1eaa)

### 🚦 期望结果 | Expected Behavior

我並不能確定是向lobe theme作者請求功能支援還是向catppuccin theme作者請求支援，因此我會在兩個存儲庫都發起issues，如若造成開發人員困擾還請見諒。
https://github.com/catppuccin/stable-diffusion-webui/issues/32

**Comment by canisminor1990** [comment]
感谢反馈，但不建议混用，目前没有计划解决多主题插件混用导致的问题
