### ISSUE TITLE
[Bug] ]提示词输入过多，超过默认的高度之后光标无法向后移动

### ISSUE THREAD

**Issue by mengluo04** [lobehub/sd-webui-lobe-theme#479]
### 👀 检查清单 | Initial checklist

- [X] 已经阅读了 [常见问题](https://github.com/lobehub/sd-webui-lobe-theme/issues/467) | I have read the [FAQ](https://github.com/lobehub/sd-webui-lobe-theme/issues/468)
- [X] 插件和 SD WebUI 均为为最新版本 | Plugin and SD WebUI both are the latest version
- [X] 插件的分支为 main | The branch of the plugin is main
- [X] 在单独开启插件的情况下，问题仍然存在 | The problem still exists when the plugin is turned on separately

### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 📦 SD Wbui 版本或提交 | Version or Commit

1.6.1

### 📦 Lobe Theme 版本或提交 | Version or Commit

25e0078a

### 🐛 问题描述 | Bug Description

提示词输入过多时，超过默认文本框高度，光标无法移动到后面，拉高输入框也不行，jishi即使鼠标选择最后提示词光标也会回到full_shot的s后面
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/32565940/ce320109-3882-4b2b-a3c9-ba9dacc8d416)

### 🚦 期望结果 | Expected Behavior

能正常切换光标位置

**Comment by kaalibro** [comment]
I'm not quite sure what exactly isn't working. Could you please record a video if possible? At least for me everything works fine.


https://github.com/lobehub/sd-webui-lobe-theme/assets/44464226/bbe67910-0051-4d5f-ae5f-d3c132091c46

**Comment by mengluo04** [comment]
> I'm not quite sure what exactly isn't working. Could you please record a video if possible? At least for me everything works fine.
> 
>  2023-12-01.11-25-12.mp4

I'm sorry, it may be because I used a third-party launcher. This problem no longer occurs after the integration package is updated.
