### ISSUE TITLE
[Bug] UI issue with Settings on desktop

### ISSUE THREAD

**Issue by Antivash** [lobehub/sd-webui-lobe-theme#491]
### 👀 检查清单 | Initial checklist

- [X] 已经阅读了 [常见问题](https://github.com/lobehub/sd-webui-lobe-theme/issues/467) | I have read the [FAQ](https://github.com/lobehub/sd-webui-lobe-theme/issues/468)
- [X] 插件和 SD WebUI 均为为最新版本 | Plugin and SD WebUI both are the latest version
- [X] 插件的分支为 main | The branch of the plugin is main
- [X] 在单独开启插件的情况下，问题仍然存在 | The problem still exists when the plugin is turned on separately

### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 📦 SD Wbui 版本或提交 | Version or Commit

1.6.1

### 📦 Lobe Theme 版本或提交 | Version or Commit

3.3.9

### 🐛 问题描述 | Bug Description

When accessing any of the categorized settings options, such as "Paths for Saving" like in this example:
![image_2023-12-15_081434290](https://github.com/lobehub/sd-webui-lobe-theme/assets/336178/d547e9ac-ab70-4c9b-8a11-8db31d2a4b5b)

... the UI smashes everything into one column of the UI, leaving things looking very cluttered and messy. See below.
![image_2023-12-15_081233018](https://github.com/lobehub/sd-webui-lobe-theme/assets/336178/27524d37-cb9e-4d42-9d43-1745b3bd472d)

Strangely, this does _not_ occur with the Show All Pages button, See:
![image_2023-12-15_081241003](https://github.com/lobehub/sd-webui-lobe-theme/assets/336178/621e5561-eeef-4337-ad09-7184e8a18d36)

This issue persists with no plugins, across all browsers.

### 🚦 期望结果 | Expected Behavior

The settings page should behave as Show All Pages globally for sorted pages as well.

### 📷 复现步骤 | Recurrence Steps

1. Install Lobe theme
2. open settings page
3. select any categorized page or show all pages

### 📝 补充信息 | Additional Information

Not sure if this should be classified as a bug or a feature request, but I would _expect_ the settings to behave identically, so I am gonna err on the side of bug. But I've seen some really dumb design decisions (Looking at you, Apple, and your floating home button). So if this _is_ intentional, it really should not be. Alternatively, if this is intended to make it more mobile friendly, a check to determine the users platform and enable/disable as needed.

**Comment by canisminor1990** [comment]
try to update to lastest stable diffusion webui version

**Comment by Antivash** [comment]
> try to update to lastest stable diffusion webui version ( FP8 or 1.7.0 RC )
Doesn't resolve it.
<details>
  <summary>Screenshots</summary>
<img src="https://i.imgur.com/GTRPoDB.png">
<img src="https://i.imgur.com/SX7OIop.png">
<img src="https://i.imgur.com/XgmVxiu.png">
</details>

 And weirdly, it changes per page... 
<details>
  <summary>Screenshots</summary>
<img src="https://i.imgur.com/GTRPoDB.png">
<img src="https://i.imgur.com/EyNDpdD.png">
<img src="https://i.imgur.com/EvDZUWQ.png">
</details>

**Comment by kaalibro** [comment]
Lobe theme does not use monospaced fonts in the UI. Do you have a user.css in the WebUI root folder?

**Comment by Antivash** [comment]
No, I use use extensions (UserCSS, Stylebot, etc) to make any changes. But even with them disabled, on a completely fresh browser profile, no extensions installed,  the issue is still persisting. 
<details>
  <summary>Screenshots</summary>
<img src="https://i.imgur.com/tSEgvVJ.png">
<img src="https://i.imgur.com/Sk4sXB8.png">
</details>

**Comment by kaalibro** [comment]
@Antivash Is this bug still present? There's no way I can reproduce it. Have you tried disabling not only Chrome extensions, but also other SD WebUI extensions? Perhaps one of them is causing a conflict.

**Comment by Antivash** [comment]
> @Antivash Is this bug still present? There's no way I can reproduce it. Have you tried disabling not only Chrome extensions, but also other SD WebUI extensions? Perhaps one of them is causing a conflict.

No, the issue is still present, but after several hours of trying various things, I stopped looking.
