### ISSUE TITLE
[Bug] Stable-Diffusion-Webui-Civitai-Helper causes Extra Networks UI to not complete loading.

### ISSUE THREAD

**Issue by inverherive** [lobehub/sd-webui-lobe-theme#494]
### 👀 检查清单 | Initial checklist

- [X] 已经阅读了 [常见问题](https://github.com/lobehub/sd-webui-lobe-theme/issues/467) | I have read the [FAQ](https://github.com/lobehub/sd-webui-lobe-theme/issues/468)
- [X] 插件和 SD WebUI 均为为最新版本 | Plugin and SD WebUI both are the latest version
- [X] 插件的分支为 main | The branch of the plugin is main
- [X] 在单独开启插件的情况下，问题仍然存在 | The problem still exists when the plugin is turned on separately

### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 📦 SD Wbui 版本或提交 | Version or Commit

1.7.0

### 📦 Lobe Theme 版本或提交 | Version or Commit

3.4.0

### 🐛 问题描述 | Bug Description

With Stable-Diffusion-Webui-Civitai-Helper extension enabled, the UI loads correctly but the .pending.svelte-1ed2p3z class doesn't get removed causing it to appear to be continuously loading.
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/25483958/eacfa5f7-78de-451c-a480-7c9be00e6a9f)

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/25483958/967c390b-3f77-4d22-86ff-717219099e4f)

### 🚦 期望结果 | Expected Behavior

UI should complete and the class removed once all loading is completed

### 📷 复现步骤 | Recurrence Steps

Enable both Webui-Civitai-Helper and Lobe

**Comment by inverherive** [comment]
Update: This seems to be tied to the number of Embeddings/Lora you have. Reducing the number of files fixes the issue. 
Broken: 3000+ embeddings and Loras
Working: ~2000 embeddings

**Comment by kaalibro** [comment]
@inverherive If this bug is still happening, try adding `--no-gradio-queue` to the COMMANDLINE_ARGS

**Comment by canisminor1990** [comment]
maybe you can try this tool to speedup preview loading https://github.com/canisminor1990/sd-webui-cover-minifier

**Comment by ostap667inbox** [comment]
> @inverherive If this bug is still happening, try adding `--no-gradio-queue` to the COMMANDLINE_ARGS

adding `--no-gradio-queue` is really the best solution if there are so many cards that the Extra Networks load becomes unstable and this block hangs on forever loading.

**Comment by inverherive** [comment]
I can confirm that --no-gradio-queue fixes my specific problem. Thanks for everyone's help.
