### ISSUE TITLE
[Request] 希望增加顶部主导航菜单的折叠功能

### ISSUE THREAD

**Issue by Sostay** [lobehub/sd-webui-lobe-theme#516]
### 🥰 需求描述 | Feature Description

顶部header主菜单有时候会遮挡掉某些界面的功能部分，希望能增加一个类似侧边栏折叠隐藏的按钮

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/6897274/17939575-6562-46f4-8e19-1df2e2e78996)

### 🧐 解决方案 | Proposed Solution

![Snipaste_2024-01-14_15-36-26](https://github.com/lobehub/sd-webui-lobe-theme/assets/6897274/3de85293-f4d6-4f5c-8ac1-2c8bb14f4528)
![Snipaste_2024-01-14_15-36-43](https://github.com/lobehub/sd-webui-lobe-theme/assets/6897274/be9f759e-745b-4114-84bf-5e351b8c8ffe)

**Comment by kaalibro** [comment]
Since this feature will only be useful for the ComfyUI extension, I think it's worth just reducing the ComfyUI container height by the header height. This way the header will not overlap the canvas.
