### ISSUE TITLE
how to change it to default interface?

### ISSUE THREAD

**Issue by lovk1y** [lobehub/sd-webui-lobe-theme#523]
### 👀 检查清单 | Initial checklist

- [X] 已经阅读了 [常见问题](https://github.com/lobehub/sd-webui-lobe-theme/issues/467) | I have read the [FAQ](https://github.com/lobehub/sd-webui-lobe-theme/issues/468)
- [X] 我已经搜索了 [issues](https://github.com/lobehub/sd-webui-lobe-theme/issues) 和 [discussions](https://github.com/lobehub/sd-webui-lobe-theme/discussions) 但无法找到帮助 | I searched [issues](https://github.com/lobehub/sd-webui-lobe-theme/issues) and [discussions](https://github.com/lobehub/sd-webui-lobe-theme/discussions) and couldn’t find anything (or linked relevant results below)

### 🧐 问题描述 | Proposed Solution

i want to change to default user interface but i can't find where and how to do it

**Comment by canisminor1990** [comment]
Switch to the extension tab, and uninstall the plugin, then reboot you webui
