### ISSUE TITLE
[Bug] Bad button spacing on model cards (conflicting extension)

### ISSUE THREAD

**Issue by nrocka** [lobehub/sd-webui-lobe-theme#552]
### 👀 检查清单 | Initial checklist

- [X] 已经阅读了 [常见问题](https://github.com/lobehub/sd-webui-lobe-theme/issues/467) | I have read the [FAQ](https://github.com/lobehub/sd-webui-lobe-theme/issues/468)
- [X] 插件和 SD WebUI 均为为最新版本 | Plugin and SD WebUI both are the latest version
- [X] 插件的分支为 main | The branch of the plugin is main
- [ ] 在单独开启插件的情况下，问题仍然存在 | The problem still exists when the plugin is turned on separately

### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 📦 SD Wbui 版本或提交 | Version or Commit

bef51aed

### 📦 Lobe Theme 版本或提交 | Version or Commit

b9ab9dc

### 🐛 问题描述 | Bug Description

First of all, the problem only occurs in combination with sd-civitai-browser-plus:
[https://github.com/BlafKing/sd-civitai-browser-plus](https://github.com/BlafKing/sd-civitai-browser-plus)

Disabling either Lobe Theme or SD Civitai Browser plus will stop the problem from occurring.

Spacing between buttons on model cards is way too large. A model card can only hold 3 buttons at a time.
The problem got more problematic with the recent a1111 update, which added more buttons and changed the way of filtering models.
First issue is, that buttons have a lot of space between each other:
![chrome_WIaEgegmWk](https://github.com/lobehub/sd-webui-lobe-theme/assets/126343531/b4a0df04-ccb1-4ab0-9577-1e4bf4217c37)

Also, the new tree view does not show model names, but only the "copy path to clipboard" button, and sometimes a portion of the "info" button:
![chrome_PwpEwOy5nu](https://github.com/lobehub/sd-webui-lobe-theme/assets/126343531/b84c3c23-ad5f-4769-8bd6-0d702ae62aa6)

(Also, the new tree view can't be resized yet, but that's less of a bug, but a "missing" feature.)

### 🚦 期望结果 | Expected Behavior

Spacing between buttons should be small, so they can all fit on the model card. For both top and bottom buttons.

### 📷 复现步骤 | Recurrence Steps

Enable extensions "sd-civitai-browser-plus" and Lobe Theme at the same time.
Disabling one of them will fix the spacing.

### 📝 补充信息 | Additional Information

I've removed the "copy path to clipboard" button from the modelcard via the corresponding HTML file, so i can use the important ones. It therefore is not visible on the first screenshot.

**Comment by 7mza** [comment]
while waiting for a solution here's a css fix you can apply using stylus or an alternative :
```
[title^='Edit metadata'],
[title^='Copy path to clipboard'],
[title^='Show internal metadata'] {
    display: none;
}
```
