### ISSUE TITLE
[Bug] init ui failed

### ISSUE THREAD

**Issue by bluelovers** [lobehub/sd-webui-lobe-theme#565]
### 👀 检查清单 | Initial checklist

- [X] 已经阅读了 [常见问题](https://github.com/lobehub/sd-webui-lobe-theme/issues/467) | I have read the [FAQ](https://github.com/lobehub/sd-webui-lobe-theme/issues/468)
- [X] 插件和 SD WebUI 均为为最新版本 | Plugin and SD WebUI both are the latest version
- [X] 插件的分支为 main | The branch of the plugin is main
- [X] 在单独开启插件的情况下，问题仍然存在 | The problem still exists when the plugin is turned on separately

### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/167966/31b200d7-4fbd-43a7-9597-c375ea85e46f)

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/167966/168f751c-b578-46d0-95dd-3b1d90a4b3d4)

**Comment by canisminor1990** [comment]
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/17870709/7d12a253-febe-4a7f-b25d-c35749d74979)

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/17870709/9342d1e1-181d-4cb6-bff6-1a91e54b20e9)

How to reproduce ?

**Comment by WangGosh** [comment]
我也出现了这个问题，昨天还好的，今天打开webui  一直处于自定义界面初始化中
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/163592591/9e30e1aa-c665-4513-a8c5-4458f1304a8f)

**Comment by bluelovers** [comment]
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/167966/d3ad4651-f975-4a06-b479-55487a8329c4)

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/167966/b3bff61a-de59-4208-8b20-c83f0137f607)

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/167966/ff854664-3240-47d9-bd83-9924558ddd76)

**Comment by bluelovers** [comment]
![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/167966/d7fa4865-7c52-449c-8574-f74c4084b9af)

![image](https://github.com/lobehub/sd-webui-lobe-theme/assets/167966/ab0a1cff-a531-4261-88ff-b5f57f0df386)

**Comment by bluelovers** [comment]
將版本回退到 v3.5.1 才能見到 ui 有載入
https://github.com/lobehub/sd-webui-lobe-theme/tree/v3.5.1
