### ISSUE TITLE
为什么不增加一个允许用户拖动界面模块的功能呢？[Request] 

### ISSUE THREAD

**Issue by ntf-Cinema4D-sd** [lobehub/sd-webui-lobe-theme#74]
### 🥰 需求描述 | Feature Description

作者辛苦，这个主题真的太棒了，很多人都非常喜欢使用它！

### 🧐 解决方案 | Proposed Solution

如题，希望开发这样一个功能，允许用户定义stable diffusion首页下方模块的顺序位置 👍

**Comment by imohuan** [comment]
https://github.com/canisminor1990/sd-webui-kitchen-theme/issues/86#issuecomment-1567200791
