### ISSUE TITLE
LoRA (Extra Networks) actions not loading to prompt [Bug] 

### ISSUE THREAD

**Issue by prescience-data** [lobehub/sd-webui-lobe-theme#91]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

When using the CivitaAI Helper module and clicking a LoRA (inject activation tag) or it's helper buttons, nothing triggers into the prompt textbox. 

I anticipate this is due to the CivitaAI Helper module not finding the expected selector from the base Gradio theme.  

_(Due to lack of familiarity with Gradio / WebUI backend, it may also be occurring in the server side Py code, rather than CSS targeting)_

https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/blob/61d395a0cdffb38535cf06dddd392cf293253241/javascript/civitai_helper.js#LL206C64-L206C91

```
injected.js:17 [USO] Button detection aborting due to timeout.
```

 

### 📝 补充信息 | Additional Information

Looking through their issue tracker they have #wontfix on other theme support requests, which is understandable, as maintaining each theme's relatively random css selectors would be a pain.

I think it makes more sense to invert the compatibility here, and try to mirror any important selectors within each individual theme to match the base Gradio selectors. Naturally, not all - but key ones like prompt textbox etc seems achievable. 

_("selectors" here being the Py backend targeting if that is what it turns out to be)_

### Update

Interesting - it seems to be targeting the `txt2img` textarea even when in `img2img` - Will close shortly after testing if it turns out be a hard bug in the CivitaAI module.

**Comment by prescience-data** [comment]
Interestingly, when switching to `txt2img` tab, and triggering the action buttons it works correctly. 

Then when you switch back to `img2img` tab, the injected prompts are present in this tab as well after a quick FLOC. 

When the CivitaAI module is disabled, the "basic" injection works as expected.

**Comment by Bodzijun** [comment]
In my case, the Extra Networks panel on the Vladiffsuion build plus CivitaAI Helper are not friendly with kitchen-theme. CivitaAI update button is on top of the description field and doesn't work...

**Comment by prescience-data** [comment]
I recently hit the "refresh button" bug as well myself incidentally.
